apiVersion: v1
data:
  mssql-sa-password: U2VhdHRsZTgwMA==
  username: c2E=
kind: Secret
metadata:
  name: sqlgitops1-login-secret
  namespace: mysqltest
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: sqlgitops1
  namespace: mysqltest
spec:
  limits:
    vcores: 4
  requests:
    vcores: 2
  service:
    type: LoadBalancer
  storage:
    data:
      className: ase-node-local
      size: 5Gi
    logs:
      className: ase-node-local
      size: 5Gi